name: Quality

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  quality:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build Swift Project
        run: |
          set -o pipefail
          cd OpenType
          swift build
      - name: Run Swift Tests
        run: |
          set -o pipefail
          cd OpenType
          swift test --enable-code-coverage

      - name: Run SwiftFormat Lint
        run: |
          set -o pipefail
          brew install swiftformat
          swiftformat --lint OpenType/Sources OpenType/Tests